'use client'

import { AttentionPanel } from '@/components/sandboxes/attention-panel'
import { CommitmentsPanel } from '@/components/sandboxes/commitments-panel'
import { DeliverySummary } from '@/components/sandboxes/insights/delivery-summary'
import { LearningPanel } from '@/components/sandboxes/insights/learning-panel'
import { TimelinePanel } from '@/components/sandboxes/timeline-panel'
import type { SandboxReporting } from '@/hooks/queries/use-sandbox-insights'
import type { SandboxOverview } from '@/types/sandbox'

/**
 * The tab the page opens on: where the term is, and what it is asking of you.
 *
 * The timeline leads because every chore below it is generated by a window
 * opening or closing — and because an account executive's first question is
 * always "where are we". Then the two lists of pending work, which stay two
 * lists on purpose: what the sandbox is flagging is not the same thing as what
 * you personally owe. The numbers come last, in their smallest form; the
 * reporting they belong to is a tab away.
 */
export function TodayTab({
  overview,
  reporting,
  openCommitmentId,
  onOpenCommitment,
  onNavigate,
  onResetSelection,
}: {
  overview: SandboxOverview
  reporting: SandboxReporting
  openCommitmentId: string | null
  onOpenCommitment: (id: string | null) => void
  onNavigate: (anchor: string) => void
  /** Learning links carry a scope; clear the filters before following one. */
  onResetSelection: () => void
}) {
  return (
    <div className="space-y-4">
      <TimelinePanel overview={overview} onOpenCommitment={onOpenCommitment} />

      {/* The timeline directly above already names every window that is open
          or about to open, so those two kinds would be the same fact twice. */}
      <AttentionPanel
        sandboxId={overview.sandbox.id}
        today={overview.today}
        hide={['window_open', 'window_opening']}
        onSelect={item => onNavigate(item.section)}
      />

      <CommitmentsPanel
        overview={overview}
        openId={openCommitmentId}
        onOpenChange={onOpenCommitment}
      />

      {reporting.analytics && (
        <DeliverySummary data={reporting.analytics} compact />
      )}
      <LearningPanel
        reporting={reporting}
        preview
        onNavigate={anchor => {
          onResetSelection()
          onNavigate(anchor)
        }}
      />
    </div>
  )
}
