'use client'

import { BarChart3, Download } from 'lucide-react'
import { useEffect, useMemo } from 'react'
import type { MessageBlock } from '@/types/agent'

type SvgChartBlock = Extract<MessageBlock, { kind: 'svg_chart' }>

interface Props {
  block: SvgChartBlock
}

/**
 * Renders a server-rendered (matplotlib) static chart delivered as inline SVG.
 *
 * Safety: the SVG is generated by our backend from structured data — the model
 * only supplies data values/labels, which matplotlib XML-escapes into <text>
 * nodes. The model never supplies raw markup, so embedding via
 * dangerouslySetInnerHTML is safe here. The SVG carries a viewBox, so
 * `w-full h-auto` scales it responsively.
 */
export function AgentSvgChart({ block }: Props) {
  const { svg, title, description, error } = block

  const downloadUrl = useMemo(() => {
    if (!svg || typeof window === 'undefined') return null
    return URL.createObjectURL(new Blob([svg], { type: 'image/svg+xml' }))
  }, [svg])

  useEffect(() => {
    return () => {
      if (downloadUrl) URL.revokeObjectURL(downloadUrl)
    }
  }, [downloadUrl])

  if (error || !svg) {
    return (
      <div className="my-3 rounded-lg border border-line bg-surface-1 p-4 text-sm text-ink-3">
        {title ? <span className="font-medium text-ink">{title}: </span> : null}
        Chart could not be rendered{error ? ` (${error})` : ''}.
      </div>
    )
  }

  const filename = `${
    (title || 'chart')
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/^-+|-+$/g, '')
      .slice(0, 60) || 'chart'
  }.svg`

  return (
    <div className="my-3 rounded-lg border border-line bg-surface-1 p-4">
      <div className="mb-2 flex items-center justify-between gap-3">
        <div className="flex min-w-0 items-center gap-2 text-xs text-ink-3">
          <BarChart3 className="h-3.5 w-3.5 shrink-0" />
          <span>Static chart</span>
        </div>
        {downloadUrl ? (
          <a
            href={downloadUrl}
            download={filename}
            className="inline-flex shrink-0 items-center gap-1.5 rounded-md border border-line bg-paper px-2.5 py-1 text-xs font-medium text-ink-2 transition-colors hover:bg-ds-accent-bg hover:text-ds-accent"
          >
            <Download className="h-3.5 w-3.5" />
            SVG
          </a>
        ) : null}
      </div>
      <div
        className="w-full [&>svg]:h-auto [&>svg]:w-full"
        dangerouslySetInnerHTML={{ __html: svg }}
      />
      {description ? (
        <p className="mt-2 text-xs text-ink-3">{description}</p>
      ) : null}
    </div>
  )
}
